---
title: "XGB_grid searching"
output: pdf_document
---

```{r}

#install.packages('xgboost') 

library(xgboost)
library(caret)
```


```{r}
training = read.csv("X_train.csv")


test = read.csv("X_test.csv")


trainingtarget = read.csv("Y_train.csv")



testtarget = read.csv("Y_test.csv")


dim(training)
dim(test)
dim(trainingtarget)
dim(testtarget)
```

```{r}

ALL_GENE = dim(trainingtarget)[2]
NUM_GENE = ALL_GENE

NCOL = 1 
#currently 1, just for 1 gene 

#change NCOL with ncol(trainingtarget)

models<-list()
mae_list = c()
pred_list = matrix(nrow = nrow(test), ncol=NCOL)
```


```{r}
#setting up the cross-validation hyper-parameter search 

xgb_grid_1 = expand.grid(
  nrounds = c(100, 250, 500),
  eta = c(0.01, 0.1),
  max_depth = c(2, 4, 6, 8, 10),
  gamma = c(0, 1, 2, 5),
  min_child_weight = 1, 
  colsample_bytree = 1,
  subsample = 1
)

#training control parameters

xgb_trcontrol_1 = trainControl(
  method = "cv",
  number = 5,
  verboseIter = TRUE,
  returnData = FALSE,
  returnResamp = "all",
  #classProbs = FALSE,
  #summaryFunction = twoClassSummary,
  allowParallel = TRUE
)

for (i in 1:NCOL){
  
  #xgb_train = xgb.DMatrix(data = as.matrix(training), label = as.numeric(trainingtarget[,i]))
  #xgb_test = xgb.DMatrix(data = as.matrix(test), label = as.numeric(testtarget[,i]))
  
  models[[i]] <- train(training, trainingtarget[,i],
                       trControl = xgb_trcontrol_1,
                       tuneGrid = xgb_grid_1,
                       method = "xgbTree")
  
  
  predicted <- predict(models[[i]], test)
  pred_list[,i] = predicted
  
  #mae = caret::MAE(testtarget[,i], pred_y)
  #mae_list = c(mae_list, mae)

}
```


```{r}

#MODEL EVALUATIONS

residuals = testtarget[,i] - predicted
RMSE = sqrt(mean(residuals^2))

cat('The root mean square error of the test data is ', round(RMSE,3),'\n')

testtarget_mean = mean(testtarget)

# Calculate total sum of squares
tss =  sum((testtarget - testtarget_mean)^2 )

# Calculate residual sum of squares
rss =  sum(residuals^2)

# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')


#MAE

mae = caret::MAE(testtarget[,i], predicted)
mae_list
(avg_mae = mean(mae_list))
```

```{r}
cor(c(pred_list), c(testtarget[,1:NCOL]))
```


