---
title: "Xgb_1"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#installing packages 

```{r}
#install.packages('xgboost') 
library(xgboost)
library(caret)
```

#preparing the data 
```{r}
load("exp_blood_t.Rdata")
#str(exp_blood_t)

set.seed(12)

indexes <- sample(2, nrow(exp_blood_t), replace = T, prob = c(0.8, 0.2))
train <- exp_blood_t[indexes==1,]
test = exp_blood_t[indexes==2, ]

train_x = (train[ , -(1:13)])
train_y = train[,(1:13)]

test_x = (test[, -(1:13)])
test_y = test[,(1:13)]

xgb_train = xgb.DMatrix(data = train_x, label = train_y[,1])
xgb_test = xgb.DMatrix(data = test_x, label = test_y[,1])

#head(test_y)
#head(train_x)
#indexes
#dim(train_x)
#dim(train_y)
```

#fitting and prediction

```{r}
xgbc = xgboost(data = xgb_train, max.depth = 2, nrounds = 50)
print(xgbc)
```

#predict x test data 

```{r}
pred_y = predict(xgbc, xgb_test)
```

#accuracy check 

```{r}
mse = mean((test_y - pred_y)^2)
mae = caret::MAE(test_y, pred_y)
rmse = caret::RMSE(test_y, pred_y)

cat("MSE: ", mse, "MAE: ", mae, " RMSE: ", rmse)
```
#plotting the y orginal data against the y predicted data

```{r}
x = 1:length(test_y)
plot(x, test_y, col = "red", type = "l")
lines(x, pred_y, col = "blue", type = "l")
legend(x = 1, y = 38,  legend = c("original test_y", "predicted test_y"), 
       col = c("red", "blue"), box.lty = 1, cex = 0.8, lty = c(1, 1))

#blue is the predicted test_y
#red is the original test_y
```


