---
title: "XGB_grid searching"
output: pdf_document
---

```{r}

#install.packages('xgboost') 

library(xgboost)
library(caret)
```


```{r}

#load("exp_blood_t.Rdata")
#load("exp_other_t.Rdata")

training = read.csv("X_train.csv")


test = read.csv("X_test.csv")


trainingtarget = read.csv("Y_train.csv")



testtarget = read.csv("Y_test.csv")


dim(training)
dim(test)
dim(trainingtarget)
dim(testtarget)
```

```{r}

ALL_GENE = dim(trainingtarget)[2]
NUM_GENE = ALL_GENE
```


```{r}

NCOL = 1 
#currently 1, just for 1 gene 

#change NCOL with NUM_GENE

models<-list()
mae_list = c()
pred_list = matrix(nrow = nrow(test), ncol=NCOL)

#setting up the cross-validation hyper-parameter search 

xgb_grid_1 = expand.grid(
  nrounds = c(100, 500, 1000),
  eta = c(0.001, 0.01, 0.1),
  max_depth = c(2, 4, 6, 8, 10),
  gamma = c(0, 1, 2, 5),
  colsample_bytree=1,
  min_child_weight=1,
  subsample=1
  
)

#training control parameters

xgb_trcontrol_1 = trainControl(
  method = "cv",
  number = 5,
  verboseIter = TRUE,
  returnData = FALSE,
  returnResamp = "final",
  #classProbs = FALSE,
  #summaryFunction = twoClassSummary,
  allowParallel = TRUE
)

for (i in 1:NCOL){
  
  #xgb_train = xgb.DMatrix(data = as.matrix(training), label = as.numeric(trainingtarget[,i]))
  #xgb_test = xgb.DMatrix(data = as.matrix(test), label = as.numeric(testtarget[,i]))
  
  models[[i]] <- train(training, trainingtarget[,i],
                       trControl = xgb_trcontrol_1,
                       tuneGrid = xgb_grid_1,
                       method = "xgbTree")
  
  #pred_y <- predict(models[[i]], xgb_test)
  
  #mae = caret::MAE(testtarget[,i], pred_y)
  #mae_list = c(mae_list, mae)
  
  #pred_list[,i] = pred_y

}
```
what i changed: line88: the first 2 arguments of train() should be xtrain and ytrain, instead of training and test set
NOTE: I added the parameter bcs i got an error : Error: The tuning parameter grid should have columns nrounds, max_depth, eta, gamma, colsample_bytree, min_child_weight, subsample
but i left it on default

```{r}
pred_list
```

```{r}
mae_list
(avg_mae = mean(mae_list))
```

```{r}
cor(c(pred_list), c(testtarget[,1:NCOL]))
```


