---
title: "Untitled"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#indexes
LUNG_INDEX = 37
NERVE_INDEX = 40
SKIN_INDEX = 45
```

```{r echo=FALSE}
library(ggplot2)
library(tidyr)
```

```{r echo=FALSE}
files <- list.files("~/CSL/TMM_norm_filt_counts")
# files <- list.files("~/TMM_norm_filt_counts")
```

```{r echo=FALSE}
require("edgeR",quietly=TRUE)

tissue_list <- list()
file_name <- list()

c = 1
for (i in files) {
  load(paste("./TMM_norm_filt_counts/",i, sep=""))
  tissue_list[[i]] <- df
  file_name[c] = i
  c = c + 1
}
```

```{r echo=FALSE}
tissue_names = list()
global_tissue_names = list()

i = 1
for (a in file_name) {
  a = sub("TMM_filt_counts_","",a)
  a = sub(".Rdata","",a)
  tissue_names[[i]] = a
  a = unlist(strsplit(a, split=' -', fixed=TRUE))[1]
  global_tissue_names[[i]] = a
  
  i = i + 1
}
tissue_names = as.character(tissue_names)
global_tissue_names = as.character(global_tissue_names)

```

```{r echo=FALSE}
load(paste("./TMM_norm_filt_counts/TMM_filt_counts_Whole Blood.Rdata"))
df_blood = df
rownames(df_blood$cpm_tmm) <- df_blood$genes$gene_id 
colnames(df_blood$cpm_tmm) <- df_blood$samples$SUBJID
```

```{r echo=FALSE}
expression_list <- list()
# expression_list contains expressions from all tissues, the column is the shared subjects with WB

j = 1
for (df_other in tissue_list) {
 
  rownames(df_other$cpm_tmm) <- df_other$genes$gene_id 
  colnames(df_other$cpm_tmm) <- df_other$samples$SUBJID 
    
  shared_genes <- df_blood$genes$gene_id[df_blood$genes$gene_id%in%df_other$genes$gene_id] 
  shared_subjects <- df_blood$samples$SUBJID[df_blood$samples$SUBJID%in%df_other$samples$SUBJID]
  
    
  exp_blood <- df_blood$cpm_tmm[shared_genes,shared_subjects] 
  exp_other <- df_other$cpm_tmm[shared_genes,shared_subjects] 
  
  expression_list[[j]] = as.data.frame(exp_other)
  
  
  j = j + 1
}

```





```{r echo=FALSE}
prop_7_2_1 = data.frame(tissue=tissue_names, total=NA, train=NA, val=NA, test=NA)


for (i in 1:(length(expression_list)-1)) {
  df = expression_list[[i]]
  total = ncol(df)
  train = round(0.7*total)
  val = round(0.2*total)
  test = total - train - val
  
  prop_7_2_1$total[i] = total
  prop_7_2_1$train[i] = train
  prop_7_2_1$val[i] = val
  prop_7_2_1$test[i] = test
  
}
```

```{r echo=FALSE}
prop_7_2_1_long = prop_7_2_1 %>% pivot_longer(c(train, val, test), names_to="set", values_to="value")
```


```{r echo=FALSE}
ggplot(data=prop_7_2_1_long[c(109,110,111,118,119,120,133,134,135),], aes(x=set, y=value, fill = tissue)) +
  ggtitle("Sample Sizes for Train, Validation, and Test Set") + 
  xlab("Set") + ylab("Size") +
  theme(axis.text.x = element_text(hjust=1, angle = 30, size=10),
        legend.text = element_text(size=5),
        legend.key.size = unit(0.4, 'cm'),
        legend.position='bottom') +

  geom_bar(stat="identity", show.legend=FALSE) +
  geom_text(aes(label = value), size = 3, vjust=-0.5)+
  facet_wrap(~tissue)
```

```{r echo=FALSE}
ggplot(data=prop_7_2_1_long[-c(160,161,162),], aes(x=set, y=value, fill = tissue)) +
  ggtitle("Sample Sizes for Train, Validation, and Test Set") + 
  xlab("Set") + ylab("Size") +
  theme(axis.text.x = element_text(hjust=1, angle = 30, size=2),
        axis.text.y = element_text(size=5),
        legend.text = element_text(size=5),
        legend.key.size = unit(0.4, 'cm'),
        legend.position='bottom',
        strip.text = element_text(size=3))+

  geom_bar(stat="identity", show.legend=FALSE) +
  geom_text(aes(label = value), size = 2, vjust=-1)+
  facet_wrap(~tissue, nrow=5)
```
