---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(edgeR)
library(mltools)
```

```{r}
# Load data needed for evaluation
dir = getwd()
load(paste0(dir,"Y_train.RData"))
load(paste0(dir,"Y_test.RData"))
load(paste0(dir,"/NN_train_pred.RData"))
load(paste0(dir,"/NN_test_pred.RData"))
load(paste0(getwd(),"/XGB_training_pred.RData"))
load(paste0(getwd(),"/XGB_test_pred.RData"))
```




```{r}
get_corr = function(pred, actual) {
  # Calculate correlation with the test target set
  correlations <- vector(length = dim(actual)[2])
  
  for(z in 1:dim(actual)[2]){
    gene <- colnames(actual)[z]
    correlations[z] <- cor(pred[,gene],actual[,gene] )
  }

  return(correlations)
}
```


```{r}
get_residual = function(pred, actual) {
  # Calculate correlation with the test target set
  
  res_matrix = matrix(nrow= dim(actual)[1],ncol=dim(actual)[2])
  
  
  for(z in 1:dim(actual)[2]){
    gene <- colnames(actual)[z]
    res_matrix[,z] <- pred[,gene]-actual[,gene]
  }

  return(res_matrix)
}
```

```{r}
res = get_residual(NN_train_pred, trainingtarget)
mse = mean(res^2)
```


```{r}
correlations = get_corr(NN_train_pred, trainingtarget)
print(median(correlations))
cor_df = as.data.frame(correlations)
  
ggplot(data = cor_df, aes(x = correlations)) + 
  ggtitle("Neural Network Training Prediction Correlation Density Plot") + 
  geom_density()
```

```{r}
correlations = get_corr(NN_test_pred, testtarget)
cor_df = as.data.frame(correlations)
  
ggplot(data = cor_df, aes(x = correlations)) + 
  ggtitle("Neural Network Test Prediction Correlation Density Plot") + 
  geom_density()
```

```{r}

```


```{r}
correlations = get_corr(XGB_train_pred, trainingtarget)
cor_df = as.data.frame(correlations)
print(median(correlations))  
ggplot(data = cor_df, aes(x = correlations)) + 
  ggtitle("XGBoost Training Prediction Correlation Density Plot") + 
  geom_density()
```

```{r}
correlations = get_corr(XGB_test_pred, testtarget)
cor_df = as.data.frame(correlations)
  
ggplot(data = cor_df, aes(x = correlations)) + 
  ggtitle("XGBoost Test Correlation Density Plot") + 
  geom_density()
```


```{r}
XGB_training_pred_ordered = XGB_train_pred[,order(colnames(XGB_train_pred))]
NN_training_pred_ordered = NN_train_pred[,order(colnames(NN_train_pred))]
# Ensemble prediction
avg_training_pred = (XGB_training_pred_ordered + NN_training_pred_ordered)/2

correlations = get_corr(avg_training_pred, trainingtarget)
print(median(correlations))  
cor_df = as.data.frame(correlations)
  
ggplot(data = cor_df, aes(x = correlations)) + 
  ggtitle("Ensemble Prediction Correlation Density Plot") + 
  geom_density()
```

```{r}
XGB_test_pred_ordered = XGB_test_pred[,order(colnames(XGB_test_pred))]
NN_test_pred_ordered = NN_test_pred[,order(colnames(NN_test_pred))]
```

```{r}
# Ensemble prediction
avg_pred = (XGB_test_pred_ordered + NN_test_pred_ordered)/2
```

```{r}
correlations = get_corr(avg_pred, testtarget)
cor_df = as.data.frame(correlations)
  
ggplot(data = cor_df, aes(x = correlations)) + 
  ggtitle("Ensemble Prediction Correlation Density Plot") + 
  geom_density()
```



```{r}
combine_df = data.frame(XGB = get_corr(XGB_test_pred, testtarget))
df = combine_df %>% pivot_longer(c(XGB), names_to="model", values_to="correlation")

ggplot() + 
  geom_density(data=df, aes(x=correlation, group=model, color=model), adjust=2) + 
  ggtitle("XGBoost Prediction Correlation Density Plot") + 
  scale_color_manual(values = c("red")) +
  xlab("Correlation") +
  ylab("Density")
```



```{r}
combine_df = data.frame(XGB = get_corr(XGB_test_pred, testtarget), NN = get_corr(NN_test_pred, testtarget))
df = combine_df %>% pivot_longer(c(XGB, NN), names_to="model", values_to="correlation")

ggplot() + 
  geom_density(data=df, aes(x=correlation, group=model, color=model), adjust=2) +
  ggtitle("Neural Network Prediction Correlation Density Plot") + 
  scale_color_manual(values = c("blue", "red")) +
  xlab("Correlation") +
  ylab("Density")
```

```{r}
combine_df = data.frame(NN = get_corr(NN_test_pred, testtarget), XGB = get_corr(XGB_test_pred, testtarget), ENSM = get_corr(avg_pred, testtarget))
df = combine_df %>% pivot_longer(c(NN, XGB, ENSM), names_to="model", values_to="correlation")

ggplot() + 
  geom_density(data=df, aes(x=correlation, group=model, color=model), adjust=2) +
  ggtitle("Ensemble Prediction Correlation Density Plot") + 
  scale_color_manual(values = c("green", "blue", "red")) +
  xlab("Correlation") +
  ylab("Density")
```


```{r}
# Get correlations from the ensemble prediction and store it in a data frame along with its corresponding gene symbol
actual = testtarget
pred = avg_pred

gene_names = vector(length = dim(actual)[2])
correlations = vector(length = dim(actual)[2])
  
for(z in 1:dim(actual)[2]){
  gene <- colnames(actual)[z]
  gene_names[z] = gene
  correlations[z] <- cor(pred[,gene],actual[,gene] )
}

df_pred_cor = data.frame(gene_names = gene_names, correlations = correlations)
```


```{r}
# Add the correlation to the Lung file
load(paste("./TMM_norm_filt_counts/TMM_filt_counts_Lung.Rdata"))
df_lung = df
df_lung_cor = data.frame(gene_names = df_lung$genes$Symbol)

# corr=NA for gene that's not in whole blood
merged_corr = merge(df_lung_cor,df_pred_cor, all.x=TRUE)

matched_corr = c()
for(i in 1:length(df_lung$genes$Symbol)) {
  matched_corr[i] = merged_corr[merged_corr$gene_names==df_lung$genes$Symbol[i],2]
}

df_lung$genes$correlations = matched_corr
save(df_lung, file="new_lung_data.RData")
```



























