---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("keras")
#install.packages("mlbench")
#install.packages("dplyr")
#install.packages("magrittr")
#install.packages("neuralnet")
#install.packages("autokeras")
```

```{r}
library(keras)
library(mlbench)
library(dplyr)
library(magrittr)
library(neuralnet)
library(tensorflow)
library("autokeras")
```

```{r}
load("./exp_blood.Rdata")
load("./exp_other.Rdata")
```

```{r}
exp_blood_t = t(exp_blood)
exp_other_t = t(exp_other)
```

```{r}
colnames(exp_blood_t) <- paste0("Blood_", colnames(exp_blood_t))
colnames(exp_other_t) <- paste0("Lung_", colnames(exp_other_t))
```

```{r}
ALL_GENE = ncol(exp_other_t)
N = nrow(exp_other_t)
```


```{r}
NUM_GENE = ALL_GENE
exp_combined = cbind(exp_blood_t[,1:NUM_GENE], exp_other_t[,1:NUM_GENE])
```

```{r}
x <- paste(c(colnames(exp_blood_t[,1:NUM_GENE])),collapse="+")
y <- paste(c(colnames(exp_other_t[,1:NUM_GENE])),collapse="+")

f <- paste(c(y, "~", x),collapse="")
```





```{r}
# Matrix

set.seed(321)

rows <- sample(nrow(exp_combined))
exp_combined_shuffled <- exp_combined[rows, ]


data = as.matrix(exp_combined_shuffled)

dimnames(data) = NULL
```

```{r}
# Scaling
data = scale(data)
```


```{r}
# Partition
train_proportion = 0.8
test_proportion = 1-train_proportion

n_train = round(N*train_proportion)
n_test = N - n_train

training = data[1:n_train, 1:NUM_GENE]
test = data[(n_train+1):N, 1:NUM_GENE]

trainingtarget = data[1:n_train, (NUM_GENE+1):(NUM_GENE*2)]
testtarget = data[(n_train+1):N, (NUM_GENE+1):(NUM_GENE*2)]

```

```{r}
#install_autokeras()
```
```{r}
#install_tensorflow()
```
```{r}
import(autokeras)
```





```{r}
library(reticulate)
py_config()
```
```{r}
library(reticulate)
py_install("autokeras")
```

```{r}
reg <- model_structured_data_regressor(max_trials = 2) %>% 
  fit(training, trainingtarget) 
```


```{r}
# 200 sample, 100 genes
small_data = training[1:200, 1:100]
```

















